### PR TITLE
preliminary support for linux-riscv64

### PR DESCRIPTION
**Pull request by mengzhuo**

### CODE REVIEW

**Comment by mengzhuo** [comment]
Done, please take a look.

**Comment by spytheman** [comment]
Looks good, except the bin/tcc file. Only the tcc.exe is expected/needed.

**Comment by mengzhuo** [comment]
> Looks good, except the bin/tcc file. Only the tcc.exe is expected/needed.

Sorry, I'm confused.
I've deleted `bin/tcc` in the PR, should I keep it?

**Comment by spytheman** [comment]
No. It is my fault - I got confused by the github UI, thinking that the file is a new one.

Everything is fine with your PR.

**Pull request merged**
